import './globals.css';
import { StorefrontProvider } from '../provider/storefront.provider';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        {/* <StorefrontProvider> */}
        <main>{children}</main>
        {/* </StorefrontProvider> */}
      </body>
    </html>
  );
}
